name: Basic Validation

on:
  push:
    branches: [ main, dev, feature/* ]
  pull_request:
    branches: [ main, dev ]
  workflow_dispatch:

jobs:
  infrastructure-validation:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "latest"
        enable-cache: true

    - name: Set up Python ${{ matrix.python-version }}
      run: uv python install ${{ matrix.python-version }}

    - name: Install dependencies
      run: uv sync --all-extras --dev

    - name: Setup virtual display (Linux)
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get install -y xvfb libxkbcommon-x11-0 libegl1-mesa libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-shape0 libxcb-xfixes0 libxcb-xinerama0
        export QT_QPA_PLATFORM=offscreen

    - name: Run CI/CD validation tests
      run: |
        uv run pytest tests/test_cicd_validation.py -v
      env:
        QT_QPA_PLATFORM: offscreen

    - name: Test core module imports
      run: |
        uv run python -c "import app.storage; import app.ui_feedback; import app.utils; import app.validation; print('All core modules imported successfully')"
      env:
        QT_QPA_PLATFORM: offscreen

    - name: Run status check
      run: |
        uv run python scripts/check-status.py
      continue-on-error: true

    - name: Generate test report
      if: always()
      run: |
        uv run pytest tests/test_cicd_validation.py --junitxml=basic-validation-${{ matrix.os }}-py${{ matrix.python-version }}.xml
      env:
        QT_QPA_PLATFORM: offscreen
      continue-on-error: true

    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: basic-validation-${{ matrix.os }}-py${{ matrix.python-version }}
        path: basic-validation-*.xml
        retention-days: 30